In [4]:
from random import randint

f1 = open('/Users/enn/Desktop/sml/assignment1/data/train.txt', 'r')

xdata = []

x1 = []
x2 = []
y1 = []
y2 = []
ydata = []
k = []
n = []
l = []

for lines in f1.readlines():
    lines = lines.replace('\n', '')
    item = lines.replace('\t', ' ').split(' ')
    l.append(item)

    for i in range(len(item)):
        if (i > 0):
            x1.append([item[0], item[i]])
            y1.append(1)
m = l  
for i in l:
    for j in m:
        k = [x for x in i if x in j]
        if k == []:
            n.append([i[0], j[0]])
            
for p in range(len(n)):
    if p % 300 == 0:
        x2.append(n[p])
        y2.append(0)
#print(len(x2))
#print(x2)
xdata = x1 + x2
print(len(xdata))
ydata = y1 + y2
print(len(ydata))

f1.close()

104830
104830


In [5]:
import tensorflow as tf


from random import randint
import numpy as np
import csv

batch_size = 1000
#how many batches
n_batch = len(xdata) // batch_size + 1
print(n_batch)
xdata = np.asarray(xdata, dtype=np.float32)
ydata = np.asarray(ydata, dtype=np.float32)
print(xdata)
print(ydata)

105
[[0.000e+00 2.860e+03]
 [0.000e+00 3.117e+03]
 [1.000e+00 3.180e+02]
 ...
 [4.084e+03 3.370e+03]
 [4.084e+03 3.678e+03]
 [4.084e+03 3.992e+03]]
[1. 1. 1. ... 0. 0. 0.]


In [3]:
import numpy as np

idx = np.arange(0 , len(train))
np.random.shuffle(idx)

x_train = [train[i] for i in idx]
y_train = [y[i] for i in idx]
#print(x_train)
#print(y_train)
print(len(x_train))
print(len(y_train))


104830
104830


In [6]:
f2 = open('/Users/enn/Desktop/sml/assignment1/data/test-public.csv', 'r')
test = f2.readlines()
testx = []
#print(test)
for line in test[1:]:
    line = line.strip('\n')
    linelist = line.split(',')
    testx.append(linelist[1:])
testx = np.asarray(testx, dtype=np.float32)
print(testx)
f2.close()

[[1.000e+00 4.021e+03]
 [2.000e+00 3.795e+03]
 [3.000e+00 1.627e+03]
 ...
 [3.946e+03 3.956e+03]
 [3.956e+03 3.969e+03]
 [4.024e+03 4.059e+03]]


In [ ]:
import json

f3 = open('/Users/enn/Desktop/sml/assignment1/data/nodes.json', 'r')
load_dict = json.load(f3)
print(load_dict)


In [7]:
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.linear_model import LogisticRegression
from sklearn import svm
from sklearn import model_selection
from sklearn.metrics import accuracy_score, classification_report

trn_data, testfile, trn_classes, test_classes = train_test_split(
    x_train,
    y_train,
    test_size = 0.3,
    random_state = 42
)

clf = svm.SVC()
clf.fit(x_train, y_train)
predictions = clf.predict(testfile)
print (accuracy_score(test_classes,predictions))


NameError: name 'x_train' is not defined

In [ ]:
import Initialize
import Evaluation_Indicators.AUC

Matrix_similarity = similarity_indicators.Salton.Salton(x_train)
        Evaluation_Indicators.AUC.Calculation_AUC(x_train, testx, Matrix_similarity, MaxNodeNum)